"""GitHub integration client for MortgageFintechOS.

Provides async GitHub API operations for issue creation, commenting,
and daily status reporting.
"""

from datetime import datetime, timezone
from typing import Any

import aiohttp
import structlog

logger = structlog.get_logger()

GITHUB_API = "https://api.github.com"


class GitHubClient:
    """Async GitHub API client for MortgageFintechOS operations."""

    def __init__(self, token: str, repo: str):
        self._token = token
        self._repo = repo
        self._log = logger.bind(component="github")
        self._headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
        }

    async def create_issue(
        self,
        title: str,
        body: str,
        labels: list[str] | None = None,
        assignees: list[str] | None = None,
    ) -> dict[str, Any]:
        url = f"{GITHUB_API}/repos/{self._repo}/issues"
        payload: dict[str, Any] = {"title": title, "body": body}
        if labels:
            payload["labels"] = labels
        if assignees:
            payload["assignees"] = assignees

        async with aiohttp.ClientSession(headers=self._headers) as session:
            async with session.post(url, json=payload) as resp:
                if resp.status == 201:
                    data = await resp.json()
                    self._log.info("issue_created", number=data["number"], title=title)
                    return {"number": data["number"], "url": data["html_url"]}
                else:
                    error = await resp.text()
                    self._log.error("issue_create_failed", status=resp.status, error=error)
                    return {"error": error, "status": resp.status}

    async def comment_on_issue(self, issue_number: int, body: str) -> dict[str, Any]:
        url = f"{GITHUB_API}/repos/{self._repo}/issues/{issue_number}/comments"
        payload = {"body": body}

        async with aiohttp.ClientSession(headers=self._headers) as session:
            async with session.post(url, json=payload) as resp:
                if resp.status == 201:
                    data = await resp.json()
                    self._log.info("comment_added", issue=issue_number)
                    return {"id": data["id"], "url": data["html_url"]}
                else:
                    error = await resp.text()
                    self._log.error("comment_failed", status=resp.status, error=error)
                    return {"error": error, "status": resp.status}

    async def post_daily_report(self, report: dict[str, Any]) -> dict[str, Any]:
        now = datetime.now(timezone.utc)
        title = f"[Daily Report] MortgageFintechOS — {now.strftime('%Y-%m-%d')}"

        body_lines = [
            "## Daily System Report",
            f"**Date:** {now.strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "### Agent Status",
        ]

        agents = report.get("agents", {})
        for name, info in agents.items():
            status_icon = "🟢" if info.get("status") == "idle" else "🔴"
            body_lines.append(
                f"- {status_icon} **{name}** — {info.get('status', 'unknown')} "
                f"| Tasks: {info.get('tasks_completed', 0)} | Errors: {info.get('error_count', 0)}"
            )

        body_lines.extend([
            "",
            "### Queue Stats",
            f"- Pending: {report.get('queue', {}).get('pending', 0)}",
            f"- Completed: {report.get('queue', {}).get('completed', 0)}",
            f"- Failed: {report.get('queue', {}).get('failed', 0)}",
            "",
            "### Health",
            f"- System: {report.get('health', 'unknown')}",
            f"- Uptime: {report.get('uptime', 'unknown')}",
            "",
            "---",
            "*Generated by MortgageFintechOS Autonomous System*",
        ])

        return await self.create_issue(
            title=title,
            body="\n".join(body_lines),
            labels=["daily-report", "automated"],
        )

    async def create_agent_task_issue(
        self,
        agent_name: str,
        task_action: str,
        result: dict[str, Any],
    ) -> dict[str, Any]:
        title = f"[{agent_name}] {task_action}"
        body_lines = [
            f"## Agent Task Result",
            f"**Agent:** {agent_name}",
            f"**Action:** {task_action}",
            f"**Timestamp:** {datetime.now(timezone.utc).isoformat()}",
            "",
            "### Result",
            "```json",
        ]

        import json
        body_lines.append(json.dumps(result, indent=2, default=str))
        body_lines.extend(["```", "", "---", "*Auto-created by MortgageFintechOS*"])

        return await self.create_issue(
            title=title,
            body="\n".join(body_lines),
            labels=[f"agent-{agent_name.lower()}", "automated"],
        )
